name: 'evs-network'

services:
  db:
    image: 'postgis/postgis:16-3.4'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: evs-network-db
    ports:
      - '5432:5432'
    volumes:
      - './pgdata:/var/lib/postgresql/data'
  redis_db:
    image: 'redis:6.2.5'
    container_name: evs-network-redis
    ports:
      - '6379:6379'
  typesense:
    environment:
      - TYPESENSE_API_KEY=xyz
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    env_file:
      - 'apps/gateway/.env'
    command: 'npm run start gateway'
    develop:
      watch:
        - action: rebuild
          path: './apps/gateway/src'
          target: '/src'
          ignore:
            - node_modules
    container_name: evs-network-gateway
    environment:
      - PORT=${DATABASE_PORT}
    ports:
      - '3000:3000'
    volumes:
        - '.:/user/src/app'
        - '/usr/src/app/node_modules'

    depends_on:
      - db
      - redis_db
      - typesense
  distribution:
    build:
      context: .
      dockerfile: apps/distribution/Dockerfile
    env_file:
      - 'apps/distribution/.env'
    command: 'npm run start distribution'
    develop:
      watch:
        - action: rebuild
          path: './apps/distribution/src'
          target: '/src'
          ignore:
            - node_modules
    container_name: evs-network-distribution
    volumes:
      - './src:/app/src'
      - '/usr/src/app/node_modules'
    depends_on:
      - db
      - redis_db
      - typesense
  search:
    build:
      context: .
      dockerfile: apps/search/Dockerfile
    env_file:
      - './apps/search/.env'
    command: 'npm run start search'
    develop:
      watch:
        - action: sync
          path: './apps/search/src'
          target: '/src'
          ignore:
            - node_modules
    container_name: evs-network-search
    volumes:
      - './src:/app/src'
      - '/usr/src/app/node_modules'
    depends_on:
      - db
      - redis_db
      - typesense
