name: 'ev-stations'

services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: ev-stations-db
    ports:
      - '5432:5432'
    volumes:
      - './pgdata:/var/lib/postgresql/data'
  typesense:
    environment:
      - TYPESENSE_API_KEY=xyz
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ev-stations
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    volumes:
      - './src:/app/src'
    depends_on:
      - db
